//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibSys.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_BookSearch1
    {
        public int accession_number { get; set; }
        public string title { get; set; }
        public string author { get; set; }
        public string bookStatus { get; set; }
    }
}
